export const SET_PAGE_NUMBER = 'SET_PAGE_NUMBER';
export const SET_SEARCH_FILTER = 'SET_SEARCH_FILTER';
export const RECIEVE_GIFS = 'RECIEVE_GIFS';
export const RECIEVE_GIFS_FOR_PAGE = 'RECIEVE_GIFS_FOR_PAGE';
export const RECIEVE_GIFS_FOR_FILTER = 'RECIEVE_GIFS_FOR_FILTER';
export const SET_MODAL_VISIBILITY = 'SET_MODAL_VISIBILITY';